# name: Publish VS Code Extension
# on:
#   push:
#     tags:
#       - '*'

# jobs:
#   build-and-publish:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: npm ci

#       - name: Increment version number
#         run: |
#           # Retrieve the current version
#           CURRENT_VERSION=$(node -pe "require('./package.json').version")

#           # Increment the version number (example: from 1.0.0 to 1.0.1)
#           MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f1)
#           MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f2)
#           PATCH=$(echo $CURRENT_VERSION | cut -d'.' -f3)
#           NEW_VERSION="${MAJOR}.${MINOR}.$(($PATCH + 1))"

#           # Update the package.json file with the new version
#           node -e "const fs = require('fs'); const packageJson = JSON.parse(fs.readFileSync('./package.json')); packageJson.version = '${NEW_VERSION}'; fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2))"

#           echo "New version: ${NEW_VERSION}"

#       - name: NPM Package
#         run: npm pack

#       - name: Publish to Visual Studio Marketplace
#         uses: actions/upload-artifact@v2
#         with:
#           name: vscode-extension
#           path: '*.vsix'
#           token: ${{ secrets.VSMARKETPLACE_TOKEN }}
